# Generated by Django 4.0.1 on 2022-03-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label_colour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='labels',
        ),
    ]
