# Generated by Django 4.0.1 on 2022-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0004_alter_cartitems_options_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered')], default='Active', max_length=20),
        ),
    ]
