# Generated by Django 4.0.1 on 2022-05-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0005_cartitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.IntegerField(null=True),
        ),
    ]
