# Generated by Django 4.0.1 on 2022-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0006_alter_cartitems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='itemtitle',
            field=models.CharField(default='x', max_length=50),
        ),
    ]
