# Generated by Django 4.0.1 on 2022-05-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0007_cartitems_itemtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='user',
            new_name='userid',
        ),
    ]
