# Generated by Django 4.0.1 on 2022-05-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0008_rename_user_cartitems_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinefood.item'),
        ),
    ]
