# Generated by Django 4.0.1 on 2022-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0009_alter_cartitems_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='location',
            field=models.CharField(default='Ktm', max_length=150),
        ),
    ]
