# Generated by Django 4.0.1 on 2022-08-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0010_remove_item_description_cartitems_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='itemtitle',
        ),
    ]
